name: update frontend content

on: 
  push:
    branches: 
      - main
    paths:
      - 'frontend/**'

  workflow_dispatch:
    branches:
      - main
    paths:
      - 'frontend/**'

permissions:
  id-token: write
  contents: read

jobs:
  updateFiles:
    runs-on: ubuntu-latest
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Logs into Azure
      - uses: azure/login@v1
        name: Sign in to Azure
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Runs Azure CLI to enable static website and copy files to container    
      - uses: azure/CLI@v1
        name: Sync new files to container and purge CDN
        with:
          inlineScript: |
            az storage blob sync -c '$web' --account-name ashearinresumeproject -s frontend/
            az cdn endpoint purge --content-paths "/*" --resource-group rg-azureResume --profile-name ashearinresumecdn --name ashearinresume